### ISSUE TITLE
Don't replace ORDER BY elements with "..."

### ISSUE THREAD

**Issue by ewjoachim** [adamchainz/django-perf-rec#143]
Ordering a query on columns or not, and the specifics of what column and in what order can be extremely relevant to understand why 2 seemingly identical queries run in either milliseconds or minutes. Given that the number of elements in the `ORDER BY` clause is generally quite limited, the interest of replacing the columns by `...` in the `ORDER BY` clause can be limited too.

I read the source of django-perf-rec and the source of sqlparse it uses, and my understanding is that this replacement is actually a side effect of sqlparse not identifying directly when a list of columns is in an `ORDER BY` or not, but I believe we could make a (probably a bit contrieved) improvement to `sql_recursively_simplify` to avoid that. Would it be accepted as a PR ? Would it need a special setting ?

I think the idea would be that whatever (non whitespace) token follows a `Keyword.ORDER` and a `Keyword.BY` would be left as-is.

**Comment by adamchainz** [comment]
SGTM
