### ISSUE TITLE
Add option/flag to provide full output in pytest

### ISSUE THREAD

**Issue by rixx** [adamchainz/django-perf-rec#188]
At least for my setup, pytest doesn't show the full diff even with `-vvv` flags, so adding an option to log to stdout even with pytest would be appreciated.

**Comment by adamchainz** [comment]
What versions of django, pytest, and pytest-django are you on? Maybe something changed...

**Comment by rixx** [comment]
```
django==2.2.1
pytest==4.4.1
pytest-django==3.4.8
```
says `pip freeze`.
