### ISSUE TITLE
Always quote queries in YAML and assertion output

### ISSUE THREAD

**Issue by danpalmer** [adamchainz/django-perf-rec#262]
This is a minor usability/ergonomics suggestion.

The `#` character, when proceeded by whitespace, indicates a comment in YAML. As queries change this can mean the developer needs to recognise when quotes need to be added, or when they could be dropped. Also copying/pasting from assertion errors may require the addition of quotes.

**Comment by adamchainz** [comment]
It doesn't seem pyyaml has an option to do this, but perhaps it's possible by overriding the dumping class.

Anyway, the intended workflow to save query updates is to delete the files and rerun, like VCR.py cassette files. Perhaps the assertion message can provide more clues there?

**Comment by danpalmer** [comment]
If that's the intended workflow, then maybe a `--rewrite-queries-on-failure` option could be good?

**Comment by adamchainz** [comment]
We can't add options to the django test runner without requiring users to subclass a custom test runner. For pytest it's a little easier, they can be added in a `pytest_configure` hook. If you made a PR with either feature I'd accept it.

**Comment by danpalmer** [comment]
Fair point. I think given how minor this usability improvement might be, and how difficult it might be to add (for unittest), it's probably not worth doing. I found this in the process of working around #261, but with PR #263 addressing that, I think this may not be much of a problem.
