### ISSUE TITLE
subquery

### ISSUE THREAD

**Issue by tolomea** [adamchainz/django-perf-rec#310]
I have one line that ends "subquery" (and for extra win that line got 90% shorter in the 2.2->3.0 transition) do you have any idea where that comes from?

**Comment by adamchainz** [comment]
Sometimes the ORM uses a subquery to select things out of, like `SELECT ... FROM () subquery`: https://github.com/django/django/blob/53d229ff632c2a3e547f2820a94239f38ba4d4ac/django/db/models/sql/compiler.py#L599-L624 . Is that hat you're seeing?

**Comment by tolomea** [comment]
Probably, but I don't understand that code or what I'm seeing. Maybe there's a gap in my SQL knowledge.
The first line in my perf rec is essentially:
```
- db: 'SELECT COUNT(*) FROM (SELECT ... FROM "rc" WHERE ("rc"."f_id" = #::uuid AND "rc"."ia")) subquery'
```
I've abbreviated the codebase specific identifiers but that's other wise the whole line.
What is subquery here? is it an SQL keyword I'm unaware of? or is it being replaced with something and perf rec isn't catching that expansion? or???

FWIW this is a DRF list endpoint and the second entry is
```
- db: 'SELECT ... FROM "rc" WHERE ("rc"."fi" = #::uuid AND "rc"."ia") LIMIT #'
```
which looks like the main query for the view. I assume the first line is DRF sizing the results for pagination, but I haven't verified that.

Also I know (and have mentioned elsewhere) that those '...'s are hiding subqueries.

**Comment by adamchainz** [comment]
It's an alias for the result set from the subquery, though perhaps a confusingly picked one, and Django skips the optional `AS` clause. The query is like `SELECT COUNT(*) FROM (SELECT ... FROM "rc" WHERE ...) AS "subquery"` (with PostgreSQL table quoting).

Unhiding those other fields is in issue #285 .

**Comment by tolomea** [comment]
Is the expectation then that that subquery is being used in the select on the second line?

**Comment by adamchainz** [comment]
No - the queries are completely separate.

**Comment by tolomea** [comment]
so where does subquery go?

**Comment by adamchainz** [comment]
I think to allow `COUNT(*)` to work in all circumstances, Django always wraps the SELECT for the queryset in the subquery. But it's not needed when retrieving actual rows.
