### ISSUE TITLE
Mechanism to hide some queries

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/django-perf-rec#339]
Sometimes it's useful to be able to hide queries from the test, perhaps where they aren't a valid representation of a real implementation. It's possible to hide queries from `assertNumQueries` with a fairly simpler context manager which adjusts the query history on the connection. While it's probably possible to come up with something similar for `django-perf-rec`, it would be great if this was supported directly.

I realise that at first this may seem like a bit of an odd feature, however I've got a couple of use cases where this would be very useful:
- background tasks which aren't part of the endpoint being tested, but which do get run synchronously by virtue of the test setup
- backends which hit the database and/or cache to compute a result that would (in production) be an HTTP request to a separate service

I suspect that it would also be useful to have a way to record that these hidden queries have happened, certainly I can imagine a first pass here being a mechanism to bookend them so it's easier for humans to interpret the queries being recorded.

Is this something you'd be interested in supporting?

**Comment by adamchainz** [comment]
This does seem a bit odd but I can see the utility where you can't control all queries.

I guess we could copy `capture_traceback` and add an optional callback, named `capture_op` or similar, which determines whether a given operation should be captured.

Can you make a PR?

**Comment by PeterJCLaw** [comment]
TIL about `capture_traceback`; that's really useful!
Yeah, something like that could work. I was originally thinking that consumers would have a decorator/context manager which would disable recording of queries within that context, however that would be easy enough to build on top of a callback per query :+1:
