### ISSUE TITLE
Cache key_or_keys cannot be Collections

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/django-perf-rec#344]
From what I can tell, using a `dict_keys` (i.e: the result of `dict.keys()`) as the keys passed to `cache.get_many` works fine in practice, yet django-perf-rec rejects it.
I'm guessing the same would be true if you passed a `set`, though I expect that that would work equally well too.

Is this an intentional limitation (i.e: I'm missing something in how Django operates), or should django-perf-rec allow this?

**Comment by adamchainz** [comment]
No it's not intentional, we should cast to list when capturing the op.
