### ISSUE TITLE
Django contenttypes framework caching

### ISSUE THREAD

**Issue by dominicmarmont** [adamchainz/django-perf-rec#347]
Djangos contenttypes framework performs some magical caching under the hood, which just resulted in some inconsistent performance recording for me depending on test order etc.

What's the recommended way to deal with this?

Would it be in scope of this package to handle the caching by maybe to optionally reset it before performance records?

I'm happy to give pr a go if you think this could be a worthwhile enhancement.

**Comment by adamchainz** [comment]
I recommend you call `ContentType.objects.clear_cache()` in the relevant tests’ `setUp()`. Alternatively, you could write your own wrapper function for django-perf-rec's recording to do this before each recording.

I don't think any such extension is in scope for django-perf-rec.

**Comment by ben-davis** [comment]
I opted to force all `ContentType` objects be cached at the beginning of the test run:

```python
model_classes = [model for model in apps.get_models()]
ContentType.objects.get_for_models(*model_classes)
```

**Comment by adamchainz** [comment]
I'd accept a PR to document that @ben-davis
