### ISSUE TITLE
Don't record performance on test fail

### ISSUE THREAD

**Issue by tolomea** [adamchainz/django-perf-rec#349]
When the performance log is being created and the test fails currently it can leave half a performance log which is very mildly irritating as it requires you do delete the file after you fix the test. Perhaps it should only record on successful test exit.

**Comment by adamchainz** [comment]
This is really hard to do in general since we aren't hooked into the test runner and know nothing about the current test or its status.

It could potentially be achieved by pushing the saving into a hook function passed to `TestCase.addCleanup` but idk how well that could work.

**Comment by tolomea** [comment]
does it currently happen in tear down? I had imagined a finally clause, but on reflection that seems naïve

**Comment by adamchainz** [comment]
No it happens at the end of the context manager.

If asserts are outside the `with`, they will cause the record to be written before the test failing. You could move the asserts inside the `with` to prevent this.

**Comment by tolomea** [comment]
ah, that makes sense, I had assumed they were all written together at the end of the test

**Comment by adamchainz** [comment]
I think we'll leave the behaviour as-is.
