### ISSUE TITLE
Regression in 4.8.0 for behaviour introduced in 4.6.0

### ISSUE THREAD

**Issue by danpalmer** [adamchainz/django-perf-rec#373]
Hi Adam, we've noticed that in 4.8.0 (#306) when sqlparse was upgraded, the fix we submitted that was included in 4.6.0 (#263) stopped working and the tests were reverted.

Was there a reason why the behaviour is no longer possible? Or was there a decision that it was not the desired behaviour?

We're keen to fix this again as it's causing us some pain having upgraded the library, but want to make sure we have full context before going ahead.

**Comment by adamchainz** [comment]
Complete accident/oversight when the test failed after upgrading.

**Comment by adamchainz** [comment]
See the fix in #374. Could you try this out before I cut a release?

**Comment by andatruta** [comment]
> See the fix in #374. Could you try this out before I cut a release?

Thanks @adamchainz! We've tested the new version and it solves the issues we were having.

**Comment by adamchainz** [comment]
Great, released in 4.14.0.
