### ISSUE TITLE
`MODE` option to update records rather than asserting on mismatches

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/django-perf-rec#460]
### Description

It would be great if there was a `MODE` option to overwrite existing snapshots rather than asserting that they match. This would be useful when making changes iteratively where you don't really care about the query snapshots until later in the development cycle. In such cases the "test" is applied by manually checking the resulting snapshot diff is acceptable.

Currently I do this by removing the snapshot files before each test run, however this is laborious and results in a larger than desirable diff as I've got multiple configurations which output to the same snapshot files (meaning to get a "clean" diff I'd need to run all the configurations, which adds little value and slows the development cycle).

**Comment by adamchainz** [comment]
Sounds like a good idea! Would save a lot of `rm`s. Would you like to make a PR?
