### ISSUE TITLE
overwrite MODE can result in invalid snapshot files

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/django-perf-rec#468]
### Python Version

3.9

### Django Version

3.2

### Package Version

4.20.0

### Description

If the new snapshot data are smaller than the previous ones, then `overwrite` mode can result in the file contents containing trailing data left over from the previous snapshots. In turn that data can end up being invalid YAML which then causes issues when the file is next read.

It looks like `set_and_save` needs to call [`fp.truncate()`](https://docs.python.org/3/library/io.html#io.IOBase.truncate) after `yaml.safe_dump`.

If you agree with this approach I'd be happy to put together a PR.

**Comment by adamchainz** [comment]
Thanks for the report, I released a fix in 4.20.1.

**Comment by PeterJCLaw** [comment]
Thanks! :smile:
