### ISSUE TITLE
Interaction between Django-perf-rec and Sql commenter

### ISSUE THREAD

**Issue by cosmith** [adamchainz/django-perf-rec#590]
### Python Version

3.11.0

### Django Version

4.2.2

### Package Version

4.24

### Description

Hello, thanks for this project!

I just ran into a little issue when moving our tests from TransactionTestCase to TestCase: we now have savepoints in our recordings.

Since we use [SQL Commenter](https://google.github.io/sqlcommenter/python/django/) to have more info in our query plans on Google Cloud SQL, our SQL queries look like this:

```
ROLLBACK TO SAVEPOINT "s139987847644992_x3209" /*controller='v4%%3Atransports-update-loads-constraints',route='api/v4/transports/%%28%%3FP%%3Cuid%%3E%%5B%%5E/%%5D%%2B%%29/loads-constraints/%%24'*/
```

The code at https://github.com/adamchainz/django-perf-rec/blob/main/src/django_perf_rec/sql.py#L123 checks that `len(node.tokens) == 7` which is not the case for us because of the comments.

I have tested removing the length condition and it works fine.

I'm happy to submit a PR, however there might be other ways of fixing this:
- getting rid of comments altogether since they won't have an impact on performance anyway
- removing this length check (not sure why it's needed in the first place?)
- disabling sqlcommenter in our tests (but I like to run my tests as close as possible to the production config)

Let me know what you think!

**Comment by adamchainz** [comment]
I think go ahead and open a PR. Please provide a test and changelog note. I’d rather not strip comments since they probably contain useful info!
